version: '3'
services:
#Redis server
 redis:
  image: redis
  container_name: redis
#  restart: always
  ports:
   - "6379:6379"
  networks:
   - public
  command: redis-server --requirepass smart


#mariaDB
 mariadb:
  image: mariadb
  container_name: database
#  restart: always
  environment: 
   MYSQL_ROOT_PASSWORD: smart
   MYSQL_DATABASE: smart
   MYSQL_USER: root
   MYSQL_PASSWORD: smart
  volumes:
   - mariadbsqldata:/var/lib/mysql
  ports:
   - "3306:3306"
  networks:
    - public

#php myadmin server
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
#  restart: always
  links:
    - mariadb:mysql
  environment:
   - VIRTUAL_HOST=db.careerexpo.com
   - PMA_HOST=mariadb
   - PMA_PORT=3306
  ports:
   - "8080:80"
  networks:
   - public


#elasticsearch
 elasticsearch:
  image: elasticsearch:6.7.0
  # image: elasticsearch:7.12.0
  container_name: elasticsearch
  environment:
   - discovery.type=single-node
   - cluster.name=elasticsearch
   - discovery.zen.minimum_master_nodes=1
  ulimits:
    memlock:
      soft: -1
      hard: -1
  ports:
   - "9200:9200"
   - "9300:9300"
  networks:
   - public

#kibana
 kibana:
  image: docker.elastic.co/kibana/kibana:6.7.0
  # image: docker.elastic.co/kibana/kibana:7.11.2
  container_name: kibana
  ports:
    - "5601:5601"
  networks:
   - public

volumes:
  mariadbsqldata:

networks:
 public: